apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
  labels:
    app: api-gateway-service
spec:
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
      - name: api-gateway-service
        image: api-gateway-service
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: USER_SERVICE_URL
          value: http://user-service:80
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
