namespace:
- path: metadata/namespace
  kind: Deployment
- path: metadata/namespace
  kind: Service
- path: metadata/namespace
  kind: ConfigMap
- path: metadata/namespace
  kind: Secret
- path: metadata/namespace
  kind: Ingress
# VirtualService の namespace を上書きしない
