apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nash-previews
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: k-wa-wa
        repo: nash
      requeueAfterSeconds: 60
  template:
    metadata:
      name: 'nash-pr-{{number}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/k-wa-wa/nuage-cluster
        targetRevision: master
        path: manifests/apps/ops/overlays/preview
        kustomize:
          commonLabels:
            app: nash-preview
          images:
            - 'ghcr.io/k-wa-wa/nash:pr-{{number}}'
          patches:
          - target:
              kind: VirtualService
              name: nash-virtualservice
            patch: |-
              - op: replace
                path: /metadata/name
                value: nash-pr-{{number}}-virtualservice
              - op: replace
                path: /spec/hosts/0
                value: nash-pr-{{number}}.dev.nuage
              - op: replace
                path: /spec/http/0/route/0/destination/host
                value: nash.nash-pr-{{number}}.svc.cluster.local

          - target:
              kind: ClusterRole
              name: pod-label-editor
            patch: |-
              - op: replace
                path: /metadata/name
                value: pod-label-editor-{{number}}
          - target:
              kind: ClusterRoleBinding
              name: label-manager-binding
            patch: |-
              - op: replace
                path: /metadata/name
                value: label-manager-binding-{{number}}
              - op: replace
                path: /subjects/0/namespace
                value: nash-pr-{{number}}
              - op: replace
                path: /roleRef/name
                value: pod-label-editor-{{number}}
          - target:
              kind: Job
              name: set-latest-label
            patch: |-
              - op: replace
                path: /metadata/name
                value: set-latest-label-{{number}}
      destination:
        server: https://kubernetes.default.svc
        namespace: 'nash-pr-{{number}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
