apiVersion: apps/v1
kind: Deployment
metadata:
  name: nash
  labels:
    app: nash
spec:
  selector:
    matchLabels:
      app: nash
  template:
    metadata:
      labels:
        app: nash
    spec:
      containers:
      - name: nash
        image: ghcr.io/k-wa-wa/nash
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nash
spec:
  selector:
    app: nash
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
