apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: keel
    repo: https://charts.keel.sh
    releaseName: keel
    namespace: keel
    version: 1.1.0
    valuesInline:
      image:
        repository: keelhq/keel
        tag: latest
