all:
  vars:
    ansible_ssh_private_key_file: ./.ssh/id_rsa
  children:
    dns-servers:
      hosts:
        oc1-dns:
          ansible_host: 192.168.5.161
          ansible_user: ubuntu
    proxy-servers:
      hosts:
        oc1-proxy:
          ansible_host: 192.168.5.160
          ansible_user: ubuntu
    devops-servers:
      hosts:
        oc1-devops:
          ansible_host: 192.168.5.162
          ansible_user: ubuntu
    omada-controllers:
      hosts:
        oc1-omada-controller:
          ansible_host: 192.168.5.163
          ansible_user: ubuntu

    k8s-loadbalancers:
      hosts:
        load-balancer-01:
          ansible_host: 192.168.5.51
          ansible_user: ubuntu
        load-balancer-02:
          ansible_host: 192.168.5.52
          ansible_user: ubuntu
    k8s-control-planes:
      hosts:
        control-plane-01:
          ansible_host: 192.168.5.61
          ansible_user: ubuntu
        control-plane-02:
          ansible_host: 192.168.5.62
          ansible_user: ubuntu
        control-plane-03:
          ansible_host: 192.168.5.63
          ansible_user: ubuntu
    k8s-worker-nodes:
      hosts:
        worker-node-01:
          ansible_host: 192.168.5.71
          ansible_user: ubuntu
        worker-node-02:
          ansible_host: 192.168.5.72
          ansible_user: ubuntu
        worker-node-device-host-01:
          ansible_host: 192.168.5.83
          ansible_user: ubuntu
        # oc1-pi-1:
        #   ansible_host: 192.168.5.11
        #   ansible_user: ubuntu
        # oc1-pi-2:
        #   ansible_host: 192.168.5.12
        #   ansible_user: ubuntu
    nfs-servers:
      hosts:
        oc1-nfs:
          ansible_host: 192.168.5.151
          ansible_user: ubuntu
    postgres-servers:
      hosts:
        oc1-pg-1:
          ansible_host: 192.168.5.156
          ansible_user: ubuntu
        oc1-pg-2:
          ansible_host: 192.168.5.157
          ansible_user: ubuntu
        oc1-pg-3:
          ansible_host: 192.168.5.158
          ansible_user: ubuntu
