apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: ops
---
apiVersion: v1
kind: Namespace
metadata:
  name: dashboard-v2
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: pechka
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: tests
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: pg-cluster
  labels:
    istio-injection: enabled
