- name: Configure etcd environment file
  ansible.builtin.template:
    src: etcd.conf.j2
    dest: /etc/default/etcd
    mode: '0644'
  notify: Restart etcd

- name: Ensure etcd data directory exists
  ansible.builtin.file:
    path: /var/lib/etcd/default
    state: directory
    owner: etcd
    group: etcd
    mode: '0700'

- name: Ensure etcd is started and enabled
  ansible.builtin.systemd:
    name: etcd
    state: started
    enabled: true
