- name: Check if Patroni configuration exists
  ansible.builtin.stat:
    path: /etc/patroni/patroni.yml
  register: patroni_conf

- name: Wipe default postgres data directory ONLY on first run
  ansible.builtin.file:
    path: "{{ postgres_data_dir }}"
    state: absent
  # 「設定ファイルがない」かつ「データディレクトリが存在する」＝初回インストール時と判断
  when:
    - not patroni_conf.stat.exists
    - not ansible_check_mode

- name: Re-create data directory with correct permissions
  ansible.builtin.file:
    path: "{{ postgres_data_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Create patroni configuration directory
  ansible.builtin.file:
    path: /etc/patroni
    state: directory
    owner: postgres
    group: postgres
    mode: '0750'

- name: Create patroni log directory
  ansible.builtin.file:
    path: /var/log/patroni
    state: directory
    owner: postgres
    group: postgres
    mode: '0750'

- name: Configure patroni (template)
  ansible.builtin.template:
    src: patroni.yml.j2
    dest: /etc/patroni/patroni.yml
    owner: postgres
    group: postgres
    mode: '0600'
  notify: Restart patroni

- name: Copy patroni systemd unit file
  ansible.builtin.template:
    src: patroni.service.j2
    dest: /etc/systemd/system/patroni.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart patroni

- name: Ensure patroni is started and enabled
  ansible.builtin.systemd:
    name: patroni
    state: started
    enabled: true
    daemon_reload: true
