apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://download.elastic.co/downloads/eck/3.1.0/crds.yaml
- https://download.elastic.co/downloads/eck/3.1.0/operator.yaml
- es-cluster.yaml
