apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nuage-tls-cert
  namespace: istio-system
spec:
  secretName: nuage-tls-cert
  duration: 2160h # 90日間
  renewBefore: 360h # 15日前に更新開始
  dnsNames:
  - "*.nuage"
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
