meshConfig:
  accessLogFile: "/dev/stdout"
  accessLogEncoding: JSON
  accessLogFormat: |
    {
      "timestamp": "%START_TIME%",
      "remote_ip": "%DOWNSTREAM_REMOTE_ADDRESS%",
      "request_id": "%REQ(X-REQUEST-ID)%",
      "host": "%REQ(:AUTHORITY)%",
      "request": {
        "method": "%REQ(:METHOD)%",
        "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
        "protocol": "%PROTOCOL%"
      },
      "status": "%RESPONSE_CODE%",
      "bytes": "%BYTES_SENT%",
      "referer": "%REQ(REFERER)%",
      "user_agent": "%REQ(USER-AGENT)%",
      "request_time_ms": "%DURATION%"
    }
