name: user_service
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.4

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  grpc: any
  protobuf: any
  postgres: ^3.1.0
  uuid: ^4.4.0
  dart_jsonwebtoken: any
  crypto: ^3.0.3
  logging: ^1.2.0 # Using Dart's official logging package
  fixnum: any
  http: ^1.2.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: ^2.4.11
  protoc_plugin: any
