apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-bluray-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi # 必須のため最小容量を設定
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/bluray
    server: 192.168.5.151
  mountOptions:
    - vers=4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-hls-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi # 必須のため最小容量を設定
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/hls
    server: 192.168.5.151
  mountOptions:
    - vers=4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-hls-readonly-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi # 必須のため最小容量を設定
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/hls
    server: 192.168.5.151
  mountOptions:
    - vers=4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-youtube-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi # 必須のため最小容量を設定
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/youtube
    server: 192.168.5.151
  mountOptions:
    - vers=4
