apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres-cluster.yaml

helmCharts:
# requires server-side-apply
- name: cloudnative-pg
  releaseName: cnpg
  repo: https://cloudnative-pg.github.io/charts
  #version: 1.10.0
  namespace: cnpg-system
  includeCRDs: true
