apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces.yaml
- https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
- https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
- https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
- https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
- https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
- longhorn-vsc.yaml

helmCharts:
- name: longhorn
  releaseName: longhorn
  repo: https://charts.longhorn.io
  version: 1.10.0
  namespace: longhorn-system
  includeCRDs: true
  valuesFile: longhorn-values.yaml
- name: velero
  releaseName: velero
  repo: https://vmware-tanzu.github.io/helm-charts
  version: 11.1.1
  namespace: velero
  includeCRDs: true
  valuesFile: velero-values.yaml
