apiVersion: v1
kind: Service
metadata:
  name: primary
  namespace: pg-cluster
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: primary
  namespace: pg-cluster
subsets:
- addresses:
  - ip: 192.168.5.155
  ports:
  - port: 5432
