apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pvc.yaml
- file-server/

- https://github.com/argoproj/argo-workflows/releases/download/v3.6.2/quick-start-minimal.yaml
- file-server-workflow/
